### ISSUE TITLE
Further development?

### ISSUE THREAD

**Issue by laabak84** [justinschoeman/vestwoods_bms_protocol#1]
Hi, thanks for your great work in documenting the BMS for Vestwoods. I am not a developer myself, but I am playing with the thought to have a raspberry pie with a Bluetooth module to pull the status of the battery in my camper van. Would you have any suggestions on how to achieve this? Appreciate your answer.

**Comment by justinschoeman** [comment]
Unfortunately, I can't really help with that.

test.py should be enough of a framework to build your own python app, if you know python.

Otherwise ask around on the various Home Automation apps - many of them have BMS support, and someone may be willing to add this BMS too.
